### ISSUE TITLE
Build on Mac

### ISSUE THREAD

**Issue by shadowwalkersb** [GorgonCryoEM/Gorgon#15]
- [x] Dropped ~~SDKs~~
  - ~~10.10~~
  - ~~10.9~~
  - ~~10.8~~
  - ~~10.7~~
- [x] Dropped, dependency builts are not supported ~~boost and pyGORGON need to be built with -stdlib=libc++ set for both compiler & linker (CMakeLists need  to be updated)~~
  - list the websites for documentation
  - http://stackoverflow.com/questions/18139710/using-c11-in-macos-x-and-compiled-boost-libraries-conundrum
  - https://github.com/GalSim-developers/GalSim/issues/483
  - http://stackoverflow.com/questions/18389799/boost-python-undefined-symbols-error-even-though-the-lib-files-are-linked
  - http://stackoverflow.com/questions/20134223/building-a-boost-python-application-on-macos-10-9-mavericks

/cc Wiki

**Comment by shadowwalkersb** [comment]
Targeting Mac OSX versions 10.7-10.10
CMakeLists.txt updated with commit/PR/branch
Setting sysroot variable in cmake to path of the target version SDK
10.9 worked
10.8-10.9 failed due to undefined symbols
10.7 worked or failed?
Some Googling and the webistes listed in description
Result: Build Boost & Gorgon with --stdlib=libc++
After building Boost/Gorgon (?) all targets built successfully
TODO: Evaluate -std=c++11

/cc Wiki

**Comment by shadowwalkersb** [comment]
:warning: Used MacPorts python :warning: 

- [ ] 10.10
```sh
python _buildExecutableDarwin.py py2app
cd dist/gorgon.app/Contents/Resources/lib/python2.7/lib-dynload/
mv libpyGORGON.dylib libpyGORGON.so
```
- [ ] 10.8
```sh
ln -s /Users/tunaydurmaz/Files/eclipse_workspace/workspace_work/build-Gorgon/lib/x64/libpyGORGON.dylib
mv libpyGORGON.dylib libpyGORGON.so
ln -s /Users/tunaydurmaz/Files/eclipse_workspace/workspace_work/gitGorgonGithub/ExternalLibraries/boost/lib/libboost_python.dylib
ln -s /Users/tunaydurmaz/Files/eclipse_workspace/workspace_work/gitGorgonGithub/ExternalLibraries/FFTW/fftw-3.3.4-MacOSX_10.10/lib/libfftw3f.dylib
python gorgon.pyw
```
```
Traceback (most recent call last):
  File "gorgon.pyw", line 23, in <module>
    from main_window_form import MainWindowForm
  File "/Users/tunaydurmaz/Files/eclipse_workspace/workspace_work/gitGorgonGithub/Gorgon/src_py/main_window_form.py", line 10, in <module>
    from window_manager import WindowManager
  File "/Users/tunaydurmaz/Files/eclipse_workspace/workspace_work/gitGorgonGithub/Gorgon/src_py/window_manager.py", line 8, in <module>
    from camera import Camera
  File "/Users/tunaydurmaz/Files/eclipse_workspace/workspace_work/gitGorgonGithub/Gorgon/src_py/camera.py", line 10, in <module>
    from libpyGORGON import Vector3DFloat
ImportError: dlopen(/Users/tunaydurmaz/Files/eclipse_workspace/workspace_work/gitGorgonGithub/Gorgon/src_py/libpyGORGON.so, 2): Library not loaded: /Users/durmaz/Files/eclipse_workspace/workspace_work/gitGorgonBitBucket/ExternalLibraries/FFTW/fftw-3.3.4-source/../Mac/lib/libfftw3f.3.dylib
  Referenced from: /Users/tunaydurmaz/Files/eclipse_workspace/workspace_work/gitGorgonGithub/Gorgon/src_py/libpyGORGON.so
  Reason: image not found
```
- [ ] 10.7
```sh
cp ~/Gorgon/lib/libpyGORGON.dylib libpyGORGON.so
cp /opt/local/lib/libboost_python-mt.dylib .
cp /opt/local/lib/libfftw3f.dylib .

rm -rf build/ dist/
python _buildExecutableDarwin.py py2app
```

**Comment by shadowwalkersb** [comment]
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   QtGui                         	0x000000010eea3e90 QApplication::setActiveWindow(QWidget*) + 336
1   QtGui                         	0x000000010ee36d14 onApplicationWindowChangedActivation(QWidget*, bool) + 100
2   com.apple.CoreFoundation      	0x00007fff924a3eda _CFXNotificationPost + 2554
3   com.apple.Foundation          	0x00007fff93830796 -[NSNotificationCenter postNotificationName:object:userInfo:] + 64
4   com.apple.AppKit              	0x00007fff91a27a46 -[NSWindow becomeKeyWindow] + 1344
5   com.apple.AppKit              	0x00007fff91a26f04 -[NSWindow _changeKeyAndMainLimitedOK:] + 719
6   com.apple.AppKit              	0x00007fff91a2676b -[NSWindow _makeKeyRegardlessOfVisibility] + 104
7   com.apple.AppKit              	0x00007fff91a266c5 -[NSWindow makeKeyAndOrderFront:] + 25
8   QtGui                         	0x0000000109025d71 QWidgetPrivate::show_sys() + 705
9   QtGui                         	0x00000001090df671 QWidgetPrivate::show_helper() + 561
1

**Comment by shadowwalkersb** [comment]
When Gorgon is built as MODULE:
- .so in ```${CMAKE_BINARY_DIR}/lib/x64```
- install step copies it to ```${CMAKE_SOURCE_DIR}/Gorgon/src_py```
- package step makes two copies
    - ```package/dist/Gorgon.app/Contents/Resources/lib/python2.7/lib-dynload/libpyGORGON.so```
    - ```package/dist/Gorgon.app/Contents/Frameworks/libpyGORGON.so```
```
otool -L package/dist/Gorgon.app/Contents/Resources/lib/python2.7/lib-dynload/libpyGORGON.so package/dist/Gorgon.app/Contents/Frameworks/libpyGORGON.so
package/dist/Gorgon.app/Contents/Resources/lib/python2.7/lib-dynload/libpyGORGON.so:
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/GLUT.framework/Versions/A/GLUT (compatibility version 1.0.0, current version 1.0.0)
	/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.0)
	/opt/local/lib/libboost_python-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/local/lib/libfftw3f.3.dylib (compatibility version 8.0.0, current version 8.4.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
package/dist/Gorgon.app/Contents/Frameworks/libpyGORGON.so:
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/GLUT.framework/Versions/A/GLUT (compatibility version 1.0.0, current version 1.0.0)
	@executable_path/../Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.0)
	@executable_path/../Frameworks/libboost_python-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	@executable_path/../Frameworks/libfftw3f.3.dylib (compatibility version 8.0.0, current version 8.4.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```
- Removing the wrong one, still doesnt' work
```rm package/dist/Gorgon.app/Contents/Resources/lib/python2.7/lib-dynload/libpyGORGON.so```
- Finally, moving the **right one** into the **right place** works
```mv -i package/dist/Gorgon.app/Contents/Frameworks/libpyGORGON.so package/dist/Gorgon.app/Contents/Resources/lib/python2.7/lib-dynload/libpyGORGON.so```

**Comment by shadowwalkersb** [comment]
Here is copying steps of py2app
```copying file ${CMAKE_SOURCE_DIR}/libpyGORGON.so -> package/dist/Gorgon.app/Contents/Resources/lib/python2.7/lib-dynload/libpyGORGON.so```
```copying libpyGORGON.so -> package/dist/Gorgon.app/Contents/Frameworks```
